#!/usr/bin/env python
"""Compile the vendored ``.proto`` files into the committed ``_proto`` package.

The alpasim ``egodriver`` contract and the CARLA ground-truth extension under
``proto/`` are generated into ``src/carla_driver_interface/_proto``, which is checked
into git so the runtime never needs ``grpcio-tools`` installed (see
``proto/README.md``).

Run this script after updating any of those protos::

    uv run python scripts/compile_protos.py

Pass ``--check`` to verify the committed output matches the protos without writing
anything.  ``tests/test_proto_generated.py`` runs the same check.

``protoc`` emits absolute imports (``from <pkg>.v0 import x_pb2``) that only resolve
when the generated tree sits on ``sys.path``.  Since the output is nested inside this
package instead, the generated files are flattened into a single directory and their
cross-imports are rewritten to relative ones.  The descriptors themselves keep their
original ``<pkg>/v0/*.proto`` names, which is what preserves wire compatibility.
"""

from __future__ import annotations

import argparse
import difflib
import re
import shutil
import sys
import tempfile
from pathlib import Path

#: Upstream revision the vendored alpasim ``.proto`` files were copied from.
ALPASIM_REV = "68709245a5dc0f2eda4f8cb2c3aa8cbdfa913043"

#: Revision of this repository the ``carla_driver`` extension proto was taken from
#: before it was maintained here (see ``proto/README.md``).
CARLA_DRIVER_INTERFACE_REV = "af1dcd3d3ddae7739f811e414a642d72d0440386"

_REPO_ROOT = Path(__file__).resolve().parents[1]
PROTO_ROOT = _REPO_ROOT / "proto"
OUTPUT_DIR = _REPO_ROOT / "src" / "carla_driver_interface" / "_proto"

#: ``.proto`` paths (relative to :data:`PROTO_ROOT`) to compile.  Their top-level
#: packages are the single source of truth for which ``from <pkg>.v0 import`` lines
#: get rewritten to relative imports.
PROTO_FILES = (
    "alpasim_grpc/v0/common.proto",
    "alpasim_grpc/v0/sensorsim.proto",
    "alpasim_grpc/v0/egodriver.proto",
    "carla_driver/v0/carla_driver.proto",
)

#: Only ``egodriver`` declares a service this package talks to, so service stubs are
#: generated for it alone: ``common`` has no service and ``sensorsim``'s is
#: implemented by alpasim's renderer, which the CARLA runtime replaces.
GRPC_SERVICE_PROTO = "alpasim_grpc/v0/egodriver.proto"

_REGENERATE = "uv run python scripts/compile_protos.py"

#: Provenance header prepended to every generated module.
HEADER = (
    "# Generated by scripts/compile_protos.py -- do not edit.\n"
    "#\n"
    f"# Sources: NVlabs/alpasim@{ALPASIM_REV[:7]} and\n"
    f"#          hakuturu583/carla_driver_interface@{CARLA_DRIVER_INTERFACE_REV[:7]}"
    " (both Apache-2.0)\n"
    f"# Regenerate with: {_REGENERATE}\n"
)

_PACKAGES = sorted({Path(name).parts[0] for name in PROTO_FILES})
_IMPORT_PATTERN = re.compile(
    rf"^from (?:{'|'.join(re.escape(package) for package in _PACKAGES)})\.v0 import ",
    flags=re.MULTILINE,
)


def _generate(destination: Path) -> None:
    """Run ``protoc`` and write flattened, import-rewritten modules to *destination*.

    Args:
        destination: Directory to populate.  Created if missing; existing generated
            modules are replaced.

    Raises:
        SystemExit: If ``grpcio-tools`` is not installed or ``protoc`` fails.
    """
    try:
        from grpc_tools import protoc  # noqa: PLC0415
    except ImportError:  # pragma: no cover - depends on the environment
        raise SystemExit(
            "grpcio-tools is required to regenerate the protobuf modules. "
            "Install it with: uv sync --group dev (on Python 3.10-3.12)"
        ) from None

    with tempfile.TemporaryDirectory() as tmp:
        raw = Path(tmp)
        well_known = Path(protoc.__file__).parent / "_proto"
        include = [f"--proto_path={PROTO_ROOT}", f"--proto_path={well_known}"]
        passes = [
            [
                "protoc",
                *include,
                f"--python_out={raw}",
                f"--pyi_out={raw}",
                *PROTO_FILES,
            ],
            ["protoc", *include, f"--grpc_python_out={raw}", GRPC_SERVICE_PROTO],
        ]
        for args in passes:
            code = protoc.main(args)
            if code != 0:
                raise SystemExit(f"protoc failed with exit code {code}")

        destination.mkdir(parents=True, exist_ok=True)
        generated = sorted(
            path for package in _PACKAGES for path in (raw / package / "v0").iterdir()
        )
        for path in generated:
            if path.suffix not in (".py", ".pyi"):
                continue
            text = _IMPORT_PATTERN.sub("from . import ", path.read_text())
            comment = "# " if path.suffix == ".pyi" else ""
            header = "".join(f"{comment}{line}" for line in HEADER.splitlines(True))
            (destination / path.name).write_text(f"{header}\n{text}")

    (destination / "__init__.py").write_text(
        '"""Generated protobuf modules for the alpasim ``egodriver`` contract.\n'
        "\n"
        "This package is generated by ``scripts/compile_protos.py`` -- see\n"
        "``proto/README.md``.\n"
        '"""\n'
    )


def _module_names(directory: Path) -> set[str]:
    """Return the generated module file names in *directory*.

    Compiled caches and other build artefacts are ignored so that running the test suite
    before the check does not make the tree look stale.
    """
    if not directory.is_dir():
        return set()
    return {
        path.name
        for path in directory.iterdir()
        if path.is_file() and path.suffix in (".py", ".pyi")
    }


def _check() -> int:
    """Compare freshly generated output against the committed modules.

    Returns:
        ``0`` when the committed output is up to date, ``1`` otherwise.
    """
    stale = False
    with tempfile.TemporaryDirectory() as tmp:
        fresh = Path(tmp) / "_proto"
        _generate(fresh)

        expected = _module_names(fresh)
        actual = _module_names(OUTPUT_DIR)

        for name in sorted(expected - actual):
            print(f"missing generated file: {name}")
            stale = True
        for name in sorted(actual - expected):
            print(f"unexpected generated file: {name}")
            stale = True
        for name in sorted(expected & actual):
            want = (fresh / name).read_text()
            have = (OUTPUT_DIR / name).read_text()
            if want == have:
                continue
            stale = True
            print(f"--- stale: {name}")
            print(
                "".join(
                    difflib.unified_diff(
                        have.splitlines(keepends=True),
                        want.splitlines(keepends=True),
                        fromfile=f"committed/{name}",
                        tofile=f"generated/{name}",
                        n=1,
                    )
                )
            )

    if stale:
        print(
            "\nGenerated protobuf modules are out of date. Regenerate with:\n"
            f"  {_REGENERATE}"
        )
        return 1
    return 0


def main(argv: list[str] | None = None) -> int:
    """Entry point.

    Args:
        argv: Command-line arguments, defaulting to ``sys.argv[1:]``.

    Returns:
        Process exit code.
    """
    parser = argparse.ArgumentParser(description=(__doc__ or "").splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed modules are up to date instead of writing them",
    )
    args = parser.parse_args(argv)

    if args.check:
        return _check()

    if OUTPUT_DIR.is_dir():
        shutil.rmtree(OUTPUT_DIR)
    _generate(OUTPUT_DIR)
    print(f"Wrote generated protobuf modules to {OUTPUT_DIR}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
