"""Packaging a policy as an alpasim driver: a Docker image and the wizard's config.

alpasim runs its driver as a container its wizard starts (``services.driver`` in the
wizard's Hydra config: an image, and a command with a ``{port}`` the wizard fills in),
and its runtime talks to it over ``egodriver.EgodriverService``. A policy served by
this package speaks that contract already; what it needs to drop into alpasim is

* an image that serves it -- :func:`write_build_context` / :func:`build_image`
  (``carla-driver-interface alpasim build-image``): the policy and this package
  installed with pip on a Python base image, serving in ``alpasim`` mode by default;
* a driver config group for the wizard -- :func:`write_wizard_config`
  (``carla-driver-interface alpasim wizard-config``): ``driver=<name>``, found through
  ``hydra.searchpath``, runs that image as alpasim's driver service.

Nothing here imports alpasim or Docker's SDK: the image is described by a generated
Dockerfile and built by the ``docker`` CLI, and the config is plain YAML text.
"""

from __future__ import annotations

import json
import math
import os
import re
import shlex
import shutil
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Mapping, Optional, Sequence, Tuple

import numpy as np

from . import __version__

__all__ = [
    "CameraOverride",
    "DEFAULT_BASE_IMAGE",
    "DEFAULT_PORT",
    "ImageSpec",
    "POLICY_ARGS_ENV",
    "POLICY_ENV",
    "PinholeCamera",
    "WizardDriverConfig",
    "build_image",
    "parse_camera",
    "parse_pinhole",
    "parse_policy_args",
    "render_dockerfile",
    "write_build_context",
    "write_wizard_config",
]

#: The policy an image serves when its command names none (``serve --policy``).
POLICY_ENV = "CARLA_DRIVER_INTERFACE_POLICY"
#: Keyword arguments for that policy, as a JSON object.
POLICY_ARGS_ENV = "CARLA_DRIVER_INTERFACE_POLICY_ARGS"

#: Any image with ``python``, ``pip`` and ``bash`` (alpasim runs ``bash -c``) works.
DEFAULT_BASE_IMAGE = "python:3.12-slim"
#: The port an image serves on when run by itself; the wizard passes its own.
DEFAULT_PORT = 50051

#: Where alpasim mounts the run's log directory in its driver container.
ALPASIM_OUTPUT_DIR = "/mnt/output"

#: Left out of a local package copied into the build context.
_IGNORED = (
    ".git",
    ".venv",
    "venv",
    "__pycache__",
    "*.pyc",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".tox",
    "node_modules",
)


def parse_policy_args(items: Sequence[str]) -> Dict[str, Any]:
    """``["key=value", ...]`` to keyword arguments; a value is JSON when it parses.

    ``speed=8.5`` gives a float and ``name=fast`` a string; quote a string that
    would parse as JSON (``name='"8"'``).
    """
    kwargs: Dict[str, Any] = {}
    for item in items:
        key, sep, raw = item.partition("=")
        if not sep or not key.isidentifier():
            raise ValueError(f"policy argument {item!r} is not key=value")
        try:
            kwargs[key] = json.loads(raw)
        except json.JSONDecodeError:
            kwargs[key] = raw
    return kwargs


# -- the image -------------------------------------------------------------------


@dataclass
class ImageSpec:
    """What goes into a driver image."""

    #: Default policy (``serve --policy``), baked in as :data:`POLICY_ENV`.
    policy: str = "route_follower"
    policy_args: Dict[str, Any] = field(default_factory=dict)
    #: pip requirements for the policy: names (``my-policy==1.2``), URLs, or local
    #: paths (a project directory or a wheel), which are copied into the context.
    install: List[str] = field(default_factory=list)
    #: How to install this package; defaults to the running version from PyPI. A
    #: local path (this checkout, say) is copied in like any other.
    carla_driver_interface: Optional[str] = None
    base_image: str = DEFAULT_BASE_IMAGE
    #: Debian packages to install first (``libgl1`` for OpenCV, say).
    apt_packages: List[str] = field(default_factory=list)
    #: Import the policy's module at build time, so a misspelt policy fails the
    #: build rather than the first rollout.
    check_policy: bool = True

    def requirement_for_self(self) -> str:
        return self.carla_driver_interface or f"carla-driver-interface=={__version__}"


def _is_local(requirement: str) -> bool:
    return Path(requirement).expanduser().exists()


def render_dockerfile(spec: ImageSpec, requirements: Sequence[str]) -> str:
    """The Dockerfile for *spec*, installing *requirements* (context-relative paths
    for local packages, as :func:`write_build_context` lays them out)."""
    lines = [
        f"# Generated by carla-driver-interface {__version__}"
        " (`carla-driver-interface alpasim build-image`).",
        f"FROM {spec.base_image}",
        "",
        "ENV PYTHONUNBUFFERED=1 PIP_NO_CACHE_DIR=1 PIP_DISABLE_PIP_VERSION_CHECK=1",
    ]
    if spec.apt_packages:
        packages = " ".join(shlex.quote(p) for p in spec.apt_packages)
        lines += [
            "RUN apt-get update \\",
            f"    && apt-get install -y --no-install-recommends {packages} \\",
            "    && rm -rf /var/lib/apt/lists/*",
        ]
    lines += [
        "COPY packages/ /opt/carla-driver-interface/packages/",
        "WORKDIR /opt/carla-driver-interface/packages",
        # One resolution for everything, so the policy's pins and ours must agree.
        "RUN python -m pip install " + " ".join(shlex.quote(r) for r in requirements),
        "WORKDIR /",
        f"ENV {POLICY_ENV}={json.dumps(spec.policy)}",
        f"ENV {POLICY_ARGS_ENV}={json.dumps(json.dumps(spec.policy_args))}",
        "RUN carla-driver-interface --help > /dev/null",
    ]
    if spec.check_policy and ":" in spec.policy:
        module, _, attribute = spec.policy.partition(":")
        check = (
            "import importlib; getattr(importlib.import_module("
            f"{json.dumps(module)}), {json.dumps(attribute)})"
        )
        lines.append(f"RUN python -c {shlex.quote(check)}")
    lines += [
        f"EXPOSE {DEFAULT_PORT}",
        # Run by itself, the image serves alpasim; the wizard replaces the command.
        "CMD "
        + json.dumps(
            [
                "carla-driver-interface",
                "serve",
                "--mode",
                "alpasim",
                "--host",
                "0.0.0.0",
                "--port",
                str(DEFAULT_PORT),
            ]
        ),
        "",
    ]
    return "\n".join(lines)


def write_build_context(spec: ImageSpec, context_dir: Path) -> Path:
    """Lay out a Docker build context for *spec* in *context_dir*; returns the
    Dockerfile. Local packages are copied under ``packages/``."""
    context_dir = Path(context_dir)
    packages = context_dir / "packages"
    if packages.exists():
        shutil.rmtree(packages)
    packages.mkdir(parents=True)

    requirements: List[str] = []
    for index, requirement in enumerate([spec.requirement_for_self(), *spec.install]):
        if not _is_local(requirement):
            requirements.append(requirement)
            continue
        source = Path(requirement).expanduser().resolve()
        target = packages / f"{index:02d}-{source.name}"
        if source.is_dir():
            shutil.copytree(source, target, ignore=shutil.ignore_patterns(*_IGNORED))
            requirements.append(f"./{target.name}")
        else:
            # A wheel's name is its metadata; keep it under a directory instead.
            target.mkdir()
            shutil.copy2(source, target / source.name)
            requirements.append(f"./{target.name}/{source.name}")

    dockerfile = context_dir / "Dockerfile"
    dockerfile.write_text(render_dockerfile(spec, requirements))
    return dockerfile


def build_image(
    spec: ImageSpec,
    tag: str,
    context_dir: Path,
    docker: str = "docker",
    extra_args: Sequence[str] = (),
) -> None:
    """Write the build context for *spec* and build it as *tag* with ``docker build``.

    Raises:
        FileNotFoundError: *docker* is not on ``PATH``.
        subprocess.CalledProcessError: the build failed.
    """
    if shutil.which(docker) is None:
        raise FileNotFoundError(f"{docker!r} not found on PATH")
    write_build_context(spec, context_dir)
    subprocess.run(
        [docker, "build", "--tag", tag, *extra_args, str(context_dir)], check=True
    )


# -- the wizard config -----------------------------------------------------------


@dataclass(frozen=True)
class CameraOverride:
    """One entry of alpasim's ``runtime.simulation_config.cameras``."""

    logical_id: str
    width: int = 512
    height: int = 320
    frame_interval_us: int = 100_000
    shutter_duration_us: int = 30_000


_CAMERA = re.compile(r"^(?P<id>[^:]+)(?::(?P<w>\d+)x(?P<h>\d+))?(?:@(?P<hz>[\d.]+))?$")


def parse_camera(text: str) -> CameraOverride:
    """``logical_id[:WIDTHxHEIGHT][@HZ]``, e.g. ``camera_front_wide_120fov:1920x1080@10``."""
    match = _CAMERA.match(text)
    if match is None:
        raise ValueError(f"camera {text!r} is not logical_id[:WIDTHxHEIGHT][@HZ]")
    camera = CameraOverride(logical_id=match["id"])
    if match["w"]:
        camera = CameraOverride(camera.logical_id, int(match["w"]), int(match["h"]))
    if match["hz"]:
        hz = float(match["hz"])
        if hz <= 0:
            raise ValueError(f"camera {text!r}: rate must be positive")
        camera = CameraOverride(
            camera.logical_id,
            camera.width,
            camera.height,
            frame_interval_us=round(1e6 / hz),
        )
    return camera


#: A camera body (x forward, y left, z up) to its optical frame (x right, y down,
#: z forward): the optical axes as columns, in body coordinates.
_BODY_TO_OPTICAL = np.array([[0.0, 0.0, 1.0], [-1.0, 0.0, 0.0], [0.0, -1.0, 0.0]])


@dataclass(frozen=True)
class PinholeCamera:
    """An undistorted pinhole camera for alpasim's renderer to render instead.

    alpasim's ``runtime.extra_cameras`` redefines a camera the renderer has; with
    NRE the logical id must be one of the scene's own cameras
    (``camera_front_wide_120fov``, ...), whose images it then renders through
    this model and mount instead. The recorded vehicle's hood mask, drawn for the
    recorded cameras, is turned off.
    """

    logical_id: str
    #: Horizontal field of view [deg]; square pixels, principal point centred.
    hfov_deg: float
    #: Mount in the rig frame (x forward, y left, z up, origin on the ground below
    #: the rear axle) [m], and the camera body's roll, pitch, yaw about it [deg]
    #: (z-y-x, right-handed: positive pitch looks down, positive yaw looks left).
    position_m: Tuple[float, float, float] = (1.5, 0.0, 1.5)
    rpy_deg: Tuple[float, float, float] = (0.0, 0.0, 0.0)

    def rotation_xyzw(self) -> Tuple[float, float, float, float]:
        """``rig_to_camera``'s rotation: the optical frame in the rig frame."""
        from scipy.spatial.transform import Rotation

        body = Rotation.from_euler("xyz", self.rpy_deg, degrees=True)
        optical = body * Rotation.from_matrix(_BODY_TO_OPTICAL)
        x, y, z, w = (float(v) for v in optical.as_quat())
        return (x, y, z, w)

    def extra_camera(self, width: int, height: int) -> Dict[str, Any]:
        """The ``runtime.extra_cameras`` entry at *width* x *height* pixels."""
        focal = (width / 2.0) / math.tan(math.radians(self.hfov_deg) / 2.0)
        return {
            "logical_id": self.logical_id,
            "rig_to_camera": {
                "translation_m": list(self.position_m),
                "rotation_xyzw": list(self.rotation_xyzw()),
            },
            "intrinsics": {
                "model": "opencv_pinhole",
                "opencv_pinhole": {
                    "focal_length": [focal, focal],
                    "principal_point": [width / 2.0, height / 2.0],
                    "radial": [0.0] * 6,
                    "tangential": [0.0] * 2,
                    "thin_prism": [0.0] * 4,
                },
            },
            "resolution_hw": [height, width],
            "shutter_type": "GLOBAL",
        }


_PINHOLE = re.compile(r"^(?P<id>[^:]+):(?P<hfov>[\d.]+)(?:@(?P<mount>[-\d.,]+))?$")


def parse_pinhole(text: str) -> PinholeCamera:
    """``logical_id:HFOV[@X,Y,Z[,ROLL,PITCH,YAW]]`` (m, deg; see :class:`PinholeCamera`)."""
    match = _PINHOLE.match(text)
    if match is None:
        raise ValueError(
            f"pinhole camera {text!r} is not logical_id:HFOV[@X,Y,Z[,ROLL,PITCH,YAW]]"
        )
    hfov = float(match["hfov"])
    if not 0.0 < hfov < 180.0:
        raise ValueError(f"pinhole camera {text!r}: HFOV must be in (0, 180) degrees")
    camera = PinholeCamera(match["id"], hfov)
    if match["mount"]:
        values = [float(v) for v in match["mount"].split(",")]
        if len(values) not in (3, 6):
            raise ValueError(
                f"pinhole camera {text!r}: mount is X,Y,Z[,ROLL,PITCH,YAW]"
            )
        rpy = (values[3], values[4], values[5]) if len(values) == 6 else (0.0, 0.0, 0.0)
        camera = PinholeCamera(
            camera.logical_id, hfov, (values[0], values[1], values[2]), rpy
        )
    return camera


@dataclass
class WizardDriverConfig:
    """``driver=<name>`` for alpasim's wizard, running an image from :func:`build_image`."""

    name: str
    image: str
    #: Policy to serve; ``None`` keeps the one baked into the image.
    policy: Optional[str] = None
    policy_args: Dict[str, Any] = field(default_factory=dict)
    #: Extra ``host:container`` mounts (weights, say); the run's log directory is
    #: always mounted at ``/mnt/output``.
    volumes: List[str] = field(default_factory=list)
    environment: Dict[str, str] = field(default_factory=dict)
    #: Replace the runtime's cameras; empty keeps alpasim's defaults.
    cameras: List[CameraOverride] = field(default_factory=list)
    #: Render these of the cameras through a pinhole model and mount of their own
    #: (``runtime.extra_cameras``), at their resolution in :attr:`cameras`.
    pinholes: List[PinholeCamera] = field(default_factory=list)
    #: ``pull_policy`` for the image: ``missing`` uses a local build as is.
    pull_policy: str = "missing"
    max_workers: int = 8

    def command(self) -> List[str]:
        """The driver service's command; alpasim joins it with spaces for ``bash -c``."""
        command = [
            "carla-driver-interface serve --mode alpasim",
            "--host 0.0.0.0",
            "--port {port}",
            f"--max-workers {self.max_workers}",
            f"--log-file {ALPASIM_OUTPUT_DIR}/driver/carla-driver-interface-{{port}}.log",
        ]
        if self.policy is not None:
            command.append(f"--policy {shlex.quote(self.policy)}")
        for key, value in self.policy_args.items():
            command.append(f"--policy-arg {shlex.quote(f'{key}={json.dumps(value)}')}")
        return command

    def files(self) -> Dict[str, str]:
        """The config group's files, by path relative to the search-path directory."""
        if not re.fullmatch(r"[A-Za-z0-9_][A-Za-z0-9_.-]*", self.name):
            raise ValueError(f"driver name {self.name!r} is not a plain file name")
        header = (
            f"# Generated by carla-driver-interface {__version__}"
            " (`carla-driver-interface alpasim wizard-config`).\n"
        )
        driver = {
            # Written to the run's driver-config.yaml, for the record; the
            # server takes its settings from the command line.
            "kind": "carla-driver-interface",
            "image": self.image,
            "policy": self.policy,
            "policy_args": self.policy_args,
        }
        service: Dict[str, Any] = {
            "image": self.image,
            # Not built from alpasim's Dockerfile.
            "external_image": True,
            "pull_policy": self.pull_policy,
            "volumes": [f"${{wizard.log_dir}}:{ALPASIM_OUTPUT_DIR}", *self.volumes],
            "environments": [f"{k}={v}" for k, v in self.environment.items()],
            "command": self.command(),
            "replicas_per_container": 1,
        }
        services: Dict[str, Any] = {"services": {"driver": service}}
        runtime: Dict[str, Any] = {}
        if self.cameras:
            runtime["simulation_config"] = {
                "cameras": [vars(camera) for camera in self.cameras]
            }
        if self.pinholes:
            sizes = {c.logical_id: (c.width, c.height) for c in self.cameras}
            missing = [p.logical_id for p in self.pinholes if p.logical_id not in sizes]
            if missing:
                raise ValueError(
                    f"pinhole cameras {missing} need a resolution: name them in cameras"
                )
            runtime["extra_cameras"] = [
                p.extra_camera(*sizes[p.logical_id]) for p in self.pinholes
            ]
            # NRE's ego masks (the recorded vehicle's hood, per camera) are drawn
            # for the recorded cameras, not for a camera redefined here.
            runtime.setdefault("simulation_config", {})["ego_mask_rig_config_id"] = None
        if runtime:
            services["runtime"] = runtime
        return {
            f"driver/{self.name}.yaml": header
            + _yaml({"defaults": [f"{self.name}_service", "_self_"]})
            + _yaml(driver),
            # Hydra reads the package header from the first line only.
            f"driver/{self.name}_service.yaml": "# @package _global_\n"
            + header
            + _yaml(services),
        }


def write_wizard_config(config: WizardDriverConfig, out_dir: Path) -> List[Path]:
    """Write *config*'s files under *out_dir*; returns them.

    Run the wizard with ``driver=<name> hydra.searchpath=[file://<out_dir>]``.
    """
    written = []
    for relative, text in config.files().items():
        path = Path(out_dir) / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
        written.append(path)
    return written


def _yaml(value: Mapping[str, Any]) -> str:
    """Block-style YAML for plain data; scalars as JSON, which YAML reads as is."""
    return "".join(_yaml_lines(value, 0))


def _yaml_lines(value: Any, indent: int) -> List[str]:
    pad = " " * indent
    lines: List[str] = []
    if isinstance(value, Mapping):
        for key, item in value.items():
            if isinstance(item, (Mapping, list)) and item:
                lines.append(f"{pad}{key}:\n")
                lines += _yaml_lines(item, indent + 2)
            else:
                lines.append(f"{pad}{key}: {_scalar(item)}\n")
    else:
        for item in value:
            if isinstance(item, Mapping) and item:
                first, *rest = _yaml_lines(item, indent + 2)
                lines.append(f"{pad}- {first.lstrip()}")
                lines += rest
            else:
                lines.append(f"{pad}- {_scalar(item)}\n")
    return lines


def _scalar(value: Any) -> str:
    if value is None:
        return "null"
    if isinstance(value, Mapping):
        return "{}"
    if isinstance(value, list):
        return "[]"
    return json.dumps(value)


def default_context_dir(tag: str) -> Path:
    """Where ``build-image`` lays out the context unless told otherwise."""
    cache = Path(os.environ.get("XDG_CACHE_HOME", Path.home() / ".cache"))
    return cache / "carla-driver-interface" / "build" / re.sub(r"[^\w.-]", "_", tag)
